
import React from 'react';
import { motion } from 'framer-motion';

const AgentInsights = ({ insights = [] }) => {
    // If no insights provided, provide a safe fallback or return nothing
    if (!insights || insights.length === 0) {
        return null;
    }

    return (
        <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-gradient-to-br from-gray-50 to-white rounded-card shadow-card p-6 border border-gray-100 h-full"
        >
            <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-600">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <h3 className="font-bold text-gray-800">Agent Maintenance Insights</h3>
            </div>

            <div className="space-y-3">
                {insights.map((insight, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="flex items-start gap-3 p-3 bg-white rounded-lg shadow-sm border border-gray-50 hover:shadow-md transition-shadow"
                    >
                        <span className="text-blue-500 mt-1 flex-shrink-0">•</span>
                        <p className="text-sm text-gray-600 leading-relaxed font-medium">
                            {insight}
                        </p>
                    </motion.div>
                ))}
            </div>

            <div className="mt-4 pt-4 border-t border-gray-100">
                <p className="text-xs text-center text-gray-400 font-mono">
                    GENERATED BY SYSTEM AGENT
                </p>
            </div>
        </motion.div>
    );
};

export default AgentInsights;
